version: 2

before:
  hooks:
    - go mod tidy

builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64
    binary: town
    ldflags:
      - -s -w -X main.version={{.Version}}

archives:
  - format: tar.gz
    name_template: "{{ .ProjectName }}_{{ .Os }}_{{ .Arch }}"
    format_overrides:
      - goos: windows
        format: zip

checksum:
  name_template: 'checksums.txt'

changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'

brews:
  - repository:
      owner: lordzsolt
      name: town
      branch: main
    directory: packaging
    homepage: "https://github.com/lordzsolt/town"
    description: "CLI tool for exploring GitHub teams and repository ownership via CODEOWNERS"
    license: "MIT"
    install: |
      bin.install "town"
    test: |
      system "#{bin}/town", "--help"
